"""Added date to Expense

Revision ID: 377dd284260e
Revises: cac1870a046e
Create Date: 2025-12-07 16:41:37.733048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '377dd284260e'
down_revision: Union[str, Sequence[str], None] = 'cac1870a046e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'date')
    # ### end Alembic commands ###
