"""Changed added to date in Income table

Revision ID: caab0ba3a8a4
Revises: 377dd284260e
Create Date: 2025-12-15 21:11:18.824309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'caab0ba3a8a4'
down_revision: Union[str, Sequence[str], None] = '377dd284260e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('date', sa.Date(), nullable=False))
    op.drop_column('incomes', 'added')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('added', sa.DATE(), nullable=False))
    op.drop_column('incomes', 'date')
    # ### end Alembic commands ###
